USE [GPPLATFORM]
GO

/****** Object:  Table [dbo].[GPIS_USER]    Script Date: 2022-05-24 ¿ÀÈÄ 5:48:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GPIS_USER](
	[PLATFORM_NO] [varchar](10) NOT NULL,
	[USER_NO] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [varchar](30) NOT NULL,
	[USER_CODE]  AS ('KRU'+right('00000000'+CONVERT([varchar](8),[USER_NO]),(8))) PERSISTED,
	[ADD_DATE] [datetime] NULL,
	[ADD_USER_ID] [varchar](50) NULL,
	[CHANGE_DATE] [datetime] NULL,
	[CHANGE_USER_ID] [varchar](50) NULL,
	[STATUS] [varchar](1) NULL,
	[BUYER_CODE] [varchar](20) NULL,
	[SELLER_CODE] [varchar](20) NULL,
	[USER_TYPE] [varchar](1) NULL,
	[USER_NAME] [varchar](50) NULL,
	[PASSWORD] [varchar](200) NULL,
	[DIVISION_CODE] [varchar](20) NULL,
	[DEPT_CODE] [varchar](20) NULL,
	[POSITION] [varchar](50) NULL,
	[EMPLOYEE_NO] [varchar](30) NULL,
	[EMAIL] [varchar](50) NULL,
	[TEL_NO] [varchar](20) NULL,
	[CELL_NO] [varchar](20) NULL,
	[FAX_NO] [varchar](20) NULL,
	[ISENABLED] [int] NOT NULL,
	[PW_WRONG_CNT] [int] NOT NULL,
	[PW_RESET_FLAG] [varchar](1) NULL,
	[PW_RESET_DATE] [datetime] NULL,
	[LAST_LOGIN_DATE] [datetime] NULL,
	[ZIP_CODE] [varchar](10) NULL,
	[ADDRESS] [varchar](200) NULL,
	[SMS_FLAG] [varchar](1) NULL,
	[MAIL_FLAG] [varchar](1) NULL,
	[CONFIRM_USER_ID] [varchar](50) NULL,
	[CONFIRM_DATE] [datetime] NULL,
	[QUOTATION_OPTION] [varchar](7) NULL,
	[PLATFORM_ROLE] [varchar](1) NULL,
	[SNS_ONLY] [varchar](1) NOT NULL,
	[SNS_LOGIN_NAVER] [varchar](20) NULL,
	[SNS_LOGIN_NAVER_MAIL] [varchar](20) NULL,
	[SNS_LOGIN_NAVER_NAME] [varchar](20) NULL,
	[SNS_LOGIN_KAKAO] [varchar](20) NULL,
	[SNS_LOGIN_KAKAO_MAIL] [varchar](20) NULL,
	[SNS_LOGIN_KAKAO_NAME] [varchar](20) NULL,
	[GPIS_SERVICE_TERMS] [varchar](10) NULL,
	[SERVICE_AGREED_DATE] [datetime] NULL,
	[GPIS_FINANCIAL_TERMS] [varchar](10) NULL,
	[FINANCIAL_AGREED_DATE] [datetime] NULL,
	[GPIS_INFORMATION_COLLECTION] [varchar](10) NULL,
	[COLLECTION_AGREED_DATE] [datetime] NULL,
	[GPIS_INFORMATION_MARKETING] [varchar](10) NULL,
	[MARKETING_AGREED_DATE] [datetime] NULL,
	[ONLY_PARAM] [varchar](200) NULL,
	[AUTH_TYPE] [varchar](100) NULL,
	[BIRTH] [varchar](20) NULL,
	[MOBILE_CO] [varchar](50) NULL,
	[GENDER] [varchar](20) NULL,
	[SNS_LOGIN_KAKAO_DATE] [datetime] NULL,
	[SNS_LOGIN_NAVER_DATE] [datetime] NULL,
 CONSTRAINT [PK_GPIS_USER] PRIMARY KEY CLUSTERED 
(
	[PLATFORM_NO] ASC,
	[USER_NO] ASC,
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GPIS_USER] ADD  CONSTRAINT [DF__GPIS_USER__ISENA__1B9317B3]  DEFAULT ('1') FOR [ISENABLED]
GO

ALTER TABLE [dbo].[GPIS_USER] ADD  CONSTRAINT [DF__GPIS_USER__PW_WR__1C873BEC]  DEFAULT ('0') FOR [PW_WRONG_CNT]
GO

ALTER TABLE [dbo].[GPIS_USER] ADD  CONSTRAINT [DF__GPIS_USER__SNS_O__1D7B6025]  DEFAULT ('N') FOR [SNS_ONLY]
GO


